const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    info: {
      description: 'Products service API with autogenerated swagger doc',
      title: 'Products service',
      version: '1.0.0',
    },
    basePath: '/',
  },
  apis: ['routes/index.js'],
};

const specs = swaggerJsdoc(options);

module.exports = app => {
  app.use('/docs', swaggerUi.serve, swaggerUi.setup(specs));
};
